import { TASK_CATEGORIES } from "./types";
import { formatDuration } from "./utils";
import type { ChecklistResult, ProjectMeta } from "./types";

/* --------------------------- markdown export --------------------------- */

export function buildMarkdown(
  meta: ProjectMeta,
  checklist: ChecklistResult,
  readiness: number,
): string {
  const done = checklist.tasks.filter((t) => t.done).length;
  const minsLeft = checklist.tasks
    .filter((t) => !t.done)
    .reduce((s, t) => s + t.estMinutes, 0);

  const lines: string[] = [
    `# ${meta.name} — Launch Plan`,
    "",
    `**${readiness}% to launch** · ${done}/${checklist.tasks.length} steps cleared · ≈ ${formatDuration(
      minsLeft,
    )} of work left`,
    "",
    `> ${checklist.projectSummary}`,
    "",
    `- **Type:** ${meta.detectedType}`,
    `- **Stack:** ${meta.detectedStack.join(", ") || "—"}`,
    meta.builtPercent ? `- **Self-estimate at scan:** ${meta.builtPercent}% done` : "",
    "",
  ].filter(Boolean);

  for (const cat of TASK_CATEGORIES) {
    const items = checklist.tasks.filter((t) => t.category === cat);
    if (!items.length) continue;
    lines.push(`## ${cat}`, "");
    for (const t of items) {
      lines.push(
        `- [${t.done ? "x" : " "}] **${t.title}** _(${t.severity}, ~${formatDuration(
          t.estMinutes,
        )})_`,
      );
      if (t.description) lines.push(`  - ${t.description}`);
    }
    lines.push("");
  }

  lines.push("---", "_Generated by FinalStretch — finalstretch.dev_");
  return lines.join("\n");
}

/* ---------------------------- share links ----------------------------- */

interface SharePayload {
  v: 1;
  meta: ProjectMeta;
  checklist: ChecklistResult;
  builtPercent: number;
}

// Compact base64url of the JSON. Drops copilot payloads to keep the URL short.
export function encodeSharePlan(
  meta: ProjectMeta,
  checklist: ChecklistResult,
  builtPercent: number,
): string {
  const slim: SharePayload = {
    v: 1,
    meta: { ...meta, fileTree: meta.fileTree.slice(0, 40) },
    checklist: {
      ...checklist,
      tasks: checklist.tasks.map(
        ({ copilot: _c, execute: _e, ...rest }) => rest,
      ),
    },
    builtPercent,
  };
  const json = JSON.stringify(slim);
  const bytes = new TextEncoder().encode(json);
  let bin = "";
  bytes.forEach((b) => (bin += String.fromCharCode(b)));
  const b64 = typeof window !== "undefined" ? window.btoa(bin) : "";
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function decodeSharePlan(raw: string): SharePayload | null {
  try {
    const b64 = raw.replace(/-/g, "+").replace(/_/g, "/");
    const bin = window.atob(b64);
    const bytes = Uint8Array.from(bin, (c) => c.charCodeAt(0));
    const json = new TextDecoder().decode(bytes);
    const parsed = JSON.parse(json) as SharePayload;
    if (parsed?.v !== 1 || !parsed.checklist?.tasks?.length) return null;
    return parsed;
  } catch {
    return null;
  }
}

export function sharePlanUrl(
  meta: ProjectMeta,
  checklist: ChecklistResult,
  builtPercent: number,
): string {
  const origin = typeof window !== "undefined" ? window.location.origin : "https://finalstretch.dev";
  return `${origin}/?plan=${encodeSharePlan(meta, checklist, builtPercent)}`;
}
